# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Unit Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: '☁️ checkout repository'
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: '📦 install dependencies'
        uses: bahmutov/npm-install@v1

      - name: '🔍 run tests'
        run: npm run test
